module.exports={
    font: "",
    height: 0,
    photographer: "",
    photographerIG: "",
    photoID: "",
    searchTerm: "",
    text: "",
    url: "",
    width: 0,
    xstart: 10,
    ystart: 10,
    xwrap: 1000,
    maxChar: 100,
}